- README.md
- destreamer.ts
- package.json
I have modified the script in a way that hopefully is towards where we want to bring this project. 
Mainly, I wanted to implement a way to download a list of videos. At the same time, I added `yargs` as a dependency to parse arguments. 
The usage is as following:
```
node ./destreamer.js --help
Options:
--help             Show help                                         [boolean]
--version          Show version number                               [boolean]
--videoUrls                                                 [array] [required]
--username                                                 [string] [required]
--outputDirectory                                 [string] [default: "videos"]
```
I have also updated README.md.
This resolves issue #5.
> Argument parser and multiple video download

- README.md
- destreamer.ts
Exposed native youtube-dl option "--format", that gives the ability to choose audio/video format and quality.
> Added audio/video quality option

- .gitignore
- destreamer.ts
- package-lock.json
- package.json
I really hope that these changes are ok and I tried to respect the same stile of writing code as close as possible
Greetings, 
Luca
> Changes we discussed through email

- destreamer.ts
- package-lock.json
- package.json
I implemented the video and title fetch through the api
> Microsoft API implementation

- README.md
- destreamer.ts
QOL changes and improvements
Fixes #21
> Some improvements

- README.md
- destreamer.ts
- package-lock.json
- package.json
chromium does not run as root/admin unless its sandbox is disabled.
To prevent security breaches, we will not support running as privileged user.
Everyone is free to make the necessary changes to remove this restriction, in which case destreamer will not be responsible for any issue or data loss.
+ Update README
**Tested on Linux.
Please test on other OSes**
> Do not run destreamer as privileged user

- destreamer.ts
- package-lock.json
- test/test.ts
- utils.ts
- one change in package-lock.json because of an automated change while installing
- changed getVideoUrls to parseVideoUrls to be more understandable
> Minor fixes

- destreamer.ts
- package-lock.json
- test/test.ts
- utils.ts
These are the same fixes that I did on the old PR but starting from an updated tokencache and implementing all the suggestion we already discussed
> Login fixes

- destreamer.ts
https://github.com/snobu/destreamer/issues/53#issuecomment-612191305
@snobu
> Changes in the evaluation of sessionInfo

- Types.ts
- destreamer.ts
- test/test.ts
- utils.ts
I explain in a comment why i didn't use the enum.
Let me know if you have changes/suggestions, tomorrow I'll implement them, goodnight.
> Created proper error logging

- src/Metadata.ts
- src/Utils.ts
- src/destreamer.ts
now using update because chunks is float
> Fix progress bar once and for all, hopefully + minor improvement

- src/destreamer.ts
and the answer was yes, i completely forgot that events are cumulative, my bad
> fix video deletion on SIGINT

- src/destreamer.ts
> Account for addtional query parameters when parsing video ID

- README.md
- destreamer.cmd
Fixes https://github.com/snobu/destreamer/issues/111
> Fix label in .cmd script

- README.md
- src/CommandLineParser.ts
- src/Utils.ts
- src/destreamer.ts
> Fix auto rename for duplicate video titles

- src/Utils.ts
- src/destreamer.ts
Fixes https://github.com/snobu/destreamer/issues/134, thanks to @kylon.
> Fix passing arguments to Utils.ts

- src/CommandLineParser.ts
- src/Events.ts
- src/Metadata.ts
- src/PuppeteerHelper.ts
- src/Utils.ts
- src/destreamer.ts
* Some other minor refactoring as well
> Fix curly braces to comply with ESLint rules

- src/Errors.ts
Made a build as requested in CONTRIBUTING.md ✅
> Fixed a typo in an error string

- src/TokenCache.ts
- src/destreamer.ts
As per title + update on the refresh session url
> Fix corporate login

- src/Utils.ts
Fixes #184 
@RiccardoJR @s-monti97 you can clone this branch and it should fix the issue you are having
> Fix for input file with one url or ending in url causing undefined outDir

- README.md
- src/destreamer.ts
> Fix first login failing session evaluation

- README.md
- src/CommandLineParser.ts
- src/Types.ts
- src/Utils.ts
- src/VideoUtils.ts
- src/destreamer.ts
> Title template

- src/VideoUtils.ts
is there a way to let VS Code pickup the lint options automatically ?
> fix lint problems

- README.md
- src/ApiClient.ts
closes #213 
closes #214 
Not much to say here: added verbose error logging and updated specialized section in the readme
> Mino changes

- README.md
- src/ApiClient.ts
- src/CommandLineParser.ts
- src/destreamer.ts
Closes #237
Just a couple of minor fix:
- made docs clearer
- fixed a bug with the ApiClient no refreshing its session and failing to fetch the thumbnail
@snobu if could please merge this and #240, they are minor changes
> Misc fixes

- src/Errors.ts
Fix typo in `MISSING_ARIA2` and some capitalization in `Errors.ts`
> Fix typo and capitalization in Errors.ts

- README.md
> fix quotes in input file example in README.md

- README.md
Added a prerequisite for the `aria2` package to be installed when using this version.
> Added `aria2` prerequisite

- README.md
- src/CommandLineParser.ts
[Closed #344](https://github.com/snobu/destreamer/issues/344)
> Template elements are no more mandatory in final name.
